name: Deploy to ECS
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

#    - name: Build the Docker image
#      run: |
#        docker build -t hackyeah-2025 .
#
#    - name: Tag the Docker image
#      run: |
#        docker tag hackyeah-2025:latest ${{ secrets.REPOSITORY_IMAGE }}:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags:  ${{ secrets.REPOSITORY_IMAGE }}:latest

#    - name: Push the Docker image to Docker Hub
#      run: |
#        docker push ${{ secrets.REPOSITORY_IMAGE }}
